{
  "remote.SSH.defaultExtensions" = [
    "bbenoist.nix"
    # "bierner.emojisense"
    "bierner.markdown-checkbox"
    "bierner.markdown-emoji"
    "bradlc.vscode-tailwindcss"
    "eamodio.gitlens"
    "gencer.html-slim-scss-css-class-completion"
    "github.github-vscode-theme"
    "gruntfuggly.todo-tree"
    "matklad.rust-analyzer"
    "mhutchie.git-graph"
    "ms-vscode-remote.remote-ssh"
    "naumovs.color-highlight"
    "pkief.material-icon-theme"
    "scala-lang.scala"
    "scalameta.metals"
    "shardulm94.trailing-spaces"
    "tabnine.tabnine-vscode"
    "tonybaloney.vscode-pets"
    "usernamehw.errorlens"
    "vscodevim.vim"
  ];
}
