require("settings")
require("remaps")
require("lsp")

require("plugins.cmp")
require("plugins.fugitive")
require("plugins.gitsigns-nvim")
require("plugins.harpoon")
require("plugins.lualine-nvim")
require("plugins.nvim-metals")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
